{"name": "Test login with invalid username", "status": "passed", "description": "This test verifies that an error message is displayed when logging in with an invalid username.", "attachments": [{"name": "Invalid Username - Error Message", "source": "a7c4bb7a-9da1-4e34-99cc-48ff852d2057-attachment.png", "type": "image/png"}], "start": 1740409259207, "stop": 1740409262820, "uuid": "dd5b93d1-3268-46ce-9959-3377fa89e96c", "historyId": "8dfefa9403d2f0167e5ccac7cf061037", "testCaseId": "8dfefa9403d2f0167e5ccac7cf061037", "fullName": "test_form_authentication.TestFormAuthentication#test_invalid_username", "labels": [{"name": "story", "value": "Invalid Login"}, {"name": "feature", "value": "Form Authentication"}, {"name": "suite", "value": "test_form_authentication"}, {"name": "subSuite", "value": "TestFormAuthentication"}, {"name": "host", "value": "Jonathan"}, {"name": "thread", "value": "13304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_form_authentication"}]}