{"name": "Test login with invalid username", "status": "passed", "description": "This test verifies that an error message is displayed when logging in with an invalid username.", "attachments": [{"name": "Invalid Username - Error Message", "source": "dc6d78e7-3b23-4ede-8799-2c4473ba9517-attachment.png", "type": "image/png"}], "start": 1740411584443, "stop": 1740411588153, "uuid": "03d26329-46da-4dbe-8d38-9166965c2d25", "historyId": "8dfefa9403d2f0167e5ccac7cf061037", "testCaseId": "8dfefa9403d2f0167e5ccac7cf061037", "fullName": "test_form_authentication.TestFormAuthentication#test_invalid_username", "labels": [{"name": "story", "value": "Invalid Login"}, {"name": "feature", "value": "Form Authentication"}, {"name": "suite", "value": "test_form_authentication"}, {"name": "subSuite", "value": "TestFormAuthentication"}, {"name": "host", "value": "Jonathan"}, {"name": "thread", "value": "23948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_form_authentication"}]}